use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fmt;

/// Stable model identifier for the built-in local text embedding provider.
pub const LOCAL_TEXT_EMBEDDING_MODEL_ID: &str = "mentisdb-local-text";
/// Stable version label for the built-in local text embedding provider.
pub const LOCAL_TEXT_EMBEDDING_VERSION: &str = "v1";
/// Fixed dimension for the built-in local text embedding provider.
pub const LOCAL_TEXT_EMBEDDING_DIMENSION: usize = 256;

/// Stable metadata describing one embedding space.
///
/// A vector index should only contain vectors generated by the same metadata
/// tuple so similarity scores remain comparable.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub struct EmbeddingMetadata {
    /// Stable provider or model identifier.
    pub model_id: String,
    /// Fixed vector dimension for this embedding space.
    pub dimension: usize,
    /// Version label for model or preprocessing changes.
    pub embedding_version: String,
}

impl EmbeddingMetadata {
    /// Create embedding metadata with model id, vector dimension, and version.
    pub fn new(
        model_id: impl Into<String>,
        dimension: usize,
        embedding_version: impl Into<String>,
    ) -> Self {
        Self {
            model_id: model_id.into(),
            dimension: dimension.max(1),
            embedding_version: embedding_version.into(),
        }
    }
}

/// Input payload for one provider embedding request.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EmbeddingInput {
    /// Caller-defined stable id that should map back to the source document.
    pub input_id: String,
    /// Text to embed.
    pub text: String,
}

impl EmbeddingInput {
    /// Create one embedding input with a stable id and source text.
    pub fn new(input_id: impl Into<String>, text: impl Into<String>) -> Self {
        Self {
            input_id: input_id.into(),
            text: text.into(),
        }
    }
}

/// One embedding vector returned by a provider.
#[derive(Debug, Clone, PartialEq)]
pub struct EmbeddingVector {
    /// Dense numeric representation in the provider's embedding space.
    pub values: Vec<f32>,
}

impl EmbeddingVector {
    /// Wrap an embedding vector.
    pub fn new(values: Vec<f32>) -> Self {
        Self { values }
    }
}

/// Provider-agnostic batch embedding interface.
/// Pluggable embedding provider for vector sidecars.
///
/// Implement this trait to bring your own embedding model (OpenAI,
/// Anthropic, local ONNX, etc.) into MentisDB's vector search pipeline.
///
/// The daemon uses this trait to:
/// 1. Embed new thoughts when they are appended (if a vector sidecar is registered)
/// 2. Embed query text during ranked search (if vector scoring is enabled)
///
/// # Example
///
/// ```rust,ignore
/// use mentisdb::search::vector::{EmbeddingProvider, EmbeddingInput, EmbeddingVector, EmbeddingMetadata};
///
/// struct MyProvider;
/// impl EmbeddingProvider for MyProvider {
///     type Error = std::io::Error;
///     fn metadata(&self) -> &EmbeddingMetadata { /* ... */ }
///     fn embed_batch(&self, inputs: &[EmbeddingInput]) -> Result<Vec<EmbeddingVector>, Self::Error> { /* ... */ }
/// }
/// ```
pub trait EmbeddingProvider {
    /// Provider-specific embedding error.
    type Error: Error + Send + Sync + 'static;

    /// Return metadata for vectors produced by this provider.
    fn metadata(&self) -> &EmbeddingMetadata;

    /// Embed a batch of inputs in the provider's declared vector space.
    fn embed_batch(&self, inputs: &[EmbeddingInput]) -> Result<Vec<EmbeddingVector>, Self::Error>;
}

/// Non-failing error type for the built-in local text embedding provider.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LocalTextEmbeddingError;

impl fmt::Display for LocalTextEmbeddingError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("local text embedding provider does not fail")
    }
}

impl Error for LocalTextEmbeddingError {}

/// Deterministic in-process embedding provider used by `mentisdb`.
///
/// This provider hashes normalized tokens and trigrams into a fixed dense
/// vector. It is lightweight, fully local, and requires no network calls or
/// model downloads, which makes it suitable as the daemon's default sidecar
/// provider.
#[derive(Debug, Clone)]
pub struct LocalTextEmbeddingProvider {
    metadata: EmbeddingMetadata,
}

impl Default for LocalTextEmbeddingProvider {
    fn default() -> Self {
        Self::new()
    }
}

impl LocalTextEmbeddingProvider {
    /// Create the built-in local text embedding provider.
    pub fn new() -> Self {
        Self {
            metadata: EmbeddingMetadata::new(
                LOCAL_TEXT_EMBEDDING_MODEL_ID,
                LOCAL_TEXT_EMBEDDING_DIMENSION,
                LOCAL_TEXT_EMBEDDING_VERSION,
            ),
        }
    }

    fn vector_for_text(&self, text: &str) -> Vec<f32> {
        let mut vector = vec![0.0; self.metadata.dimension];
        let normalized = text.to_ascii_lowercase();
        let trimmed = normalized.trim();
        let mut token_count = 0usize;

        for token in normalized
            .split(|character: char| !character.is_ascii_alphanumeric())
            .filter(|token| !token.is_empty())
        {
            token_count += 1;
            accumulate_hashed_feature(&mut vector, token.as_bytes(), 1.0);
        }

        let compact: Vec<u8> = normalized
            .bytes()
            .filter(|byte| byte.is_ascii_alphanumeric())
            .collect();
        for trigram in compact.windows(3) {
            accumulate_hashed_feature(&mut vector, trigram, 0.35);
        }

        if token_count == 0 && !trimmed.is_empty() {
            accumulate_hashed_feature(&mut vector, trimmed.as_bytes(), 1.0);
        }
        if vector.iter().all(|value| *value == 0.0) {
            vector[0] = 1.0;
            return vector;
        }

        let magnitude = vector.iter().map(|value| value * value).sum::<f32>().sqrt();
        if magnitude > 0.0 {
            for value in &mut vector {
                *value /= magnitude;
            }
        }
        vector
    }
}

impl EmbeddingProvider for LocalTextEmbeddingProvider {
    type Error = LocalTextEmbeddingError;

    fn metadata(&self) -> &EmbeddingMetadata {
        &self.metadata
    }

    fn embed_batch(&self, inputs: &[EmbeddingInput]) -> Result<Vec<EmbeddingVector>, Self::Error> {
        Ok(inputs
            .iter()
            .map(|input| EmbeddingVector::new(self.vector_for_text(&input.text)))
            .collect())
    }
}

/// Failure while converting provider outputs into vector documents.
#[derive(Debug, PartialEq, Eq)]
pub enum EmbeddingBuildError<E> {
    /// Provider returned an error.
    Provider(E),
    /// Provider returned a different number of vectors than requested inputs.
    OutputCountMismatch {
        /// Number of input rows requested.
        expected: usize,
        /// Number of vectors returned by the provider.
        actual: usize,
    },
    /// Returned vector did not match provider metadata dimension.
    DimensionMismatch {
        /// Expected vector dimension from provider metadata.
        expected: usize,
        /// Actual vector length returned by provider.
        actual: usize,
        /// Position of the offending input/vector pair.
        input_index: usize,
    },
    /// Returned vector contained `NaN` or `inf`.
    NonFiniteValue {
        /// Position of the offending input/vector pair.
        input_index: usize,
        /// Position of the non-finite value inside the vector.
        value_index: usize,
    },
}

impl<E: fmt::Display> fmt::Display for EmbeddingBuildError<E> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Provider(error) => write!(f, "embedding provider error: {error}"),
            Self::OutputCountMismatch { expected, actual } => write!(
                f,
                "embedding provider returned {actual} vectors for {expected} inputs"
            ),
            Self::DimensionMismatch {
                expected,
                actual,
                input_index,
            } => write!(
                f,
                "embedding vector dimension mismatch at input index {input_index}: expected {expected}, got {actual}"
            ),
            Self::NonFiniteValue {
                input_index,
                value_index,
            } => write!(
                f,
                "embedding vector contains non-finite value at input index {input_index}, value index {value_index}"
            ),
        }
    }
}

impl<E: Error + 'static> Error for EmbeddingBuildError<E> {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Provider(error) => Some(error),
            _ => None,
        }
    }
}

/// Convert provider embeddings into deterministic vector documents.
pub fn embed_batch_to_documents<P: EmbeddingProvider>(
    provider: &P,
    inputs: &[EmbeddingInput],
) -> Result<Vec<VectorDocument>, EmbeddingBuildError<P::Error>> {
    let outputs = provider
        .embed_batch(inputs)
        .map_err(EmbeddingBuildError::Provider)?;
    if outputs.len() != inputs.len() {
        return Err(EmbeddingBuildError::OutputCountMismatch {
            expected: inputs.len(),
            actual: outputs.len(),
        });
    }

    let dimension = provider.metadata().dimension;
    inputs
        .iter()
        .zip(outputs)
        .enumerate()
        .map(|(input_index, (input, output))| {
            if output.values.len() != dimension {
                return Err(EmbeddingBuildError::DimensionMismatch {
                    expected: dimension,
                    actual: output.values.len(),
                    input_index,
                });
            }
            for (value_index, value) in output.values.iter().enumerate() {
                if !value.is_finite() {
                    return Err(EmbeddingBuildError::NonFiniteValue {
                        input_index,
                        value_index,
                    });
                }
            }
            Ok(VectorDocument::new(input.input_id.clone(), output.values))
        })
        .collect()
}

/// One vectorized document tracked by the index.
#[derive(Debug, Clone, PartialEq)]
pub struct VectorDocument {
    /// Stable caller-defined id for deterministic tie-breaking and lookup.
    pub document_id: String,
    /// Dense vector in a shared embedding space.
    pub vector: Vec<f32>,
}

impl VectorDocument {
    /// Create a vector document with id and vector values.
    pub fn new(document_id: impl Into<String>, vector: Vec<f32>) -> Self {
        Self {
            document_id: document_id.into(),
            vector,
        }
    }
}

/// Query payload for cosine-ranked vector retrieval.
#[derive(Debug, Clone, PartialEq)]
pub struct VectorQuery {
    /// Query vector in the same embedding space as the index.
    pub vector: Vec<f32>,
    /// Maximum number of hits to return.
    pub limit: usize,
}

impl VectorQuery {
    /// Create a query with default limit of 10.
    pub fn new(vector: Vec<f32>) -> Self {
        Self { vector, limit: 10 }
    }

    /// Set maximum number of hits to return.
    pub fn with_limit(mut self, limit: usize) -> Self {
        self.limit = limit.max(1);
        self
    }
}

/// Filter that restricts vector search to a subset of indexed documents.
///
/// `VectorFilter` is a lightweight predicate evaluated over document ids.
/// The caller is responsible for translating metadata clauses such as
/// `agent_id = "x"` or `timestamp > y` into a set of allowed ids and then into
/// a `VectorFilter` variant. The exact backend applies the filter during the
/// linear scan; the HNSW backend applies it after retrieving an oversampled
/// candidate set from the approximate graph.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VectorFilter {
    /// No filtering; semantically equivalent to [`VectorSearchBackend::search`].
    None,
    /// Include only documents whose id appears in this set.
    Ids(BTreeSet<String>),
}

impl VectorFilter {
    /// Create a filter from a collection of document ids.
    pub fn from_ids(ids: impl IntoIterator<Item = impl Into<String>>) -> Self {
        let set: BTreeSet<String> = ids.into_iter().map(Into::into).collect();
        if set.is_empty() {
            Self::None
        } else {
            Self::Ids(set)
        }
    }

    /// Return `true` if the filter allows every document.
    pub fn allows_all(&self) -> bool {
        matches!(self, Self::None)
    }

    /// Return true when `document_id` passes the filter.
    pub fn allows(&self, document_id: &str) -> bool {
        match self {
            Self::None => true,
            Self::Ids(ids) => ids.contains(document_id),
        }
    }
}

/// Ranked vector-search hit.
#[derive(Debug, Clone, PartialEq)]
pub struct VectorSearchHit {
    /// Stable document id.
    pub document_id: String,
    /// Cosine similarity score in `[-1.0, 1.0]`.
    pub score: f32,
}

/// Backend selection for [`VectorIndex`] construction.
///
/// `Exact` is the deterministic in-memory linear-scan cosine backend and is
/// always available. `Hnsw` is reserved for the upcoming approximate-nearest-
/// neighbor backend (see ROADMAP.md 1.0.0 Track B) and is selected by
/// [`select_backend_kind`] once the corpus crosses
/// [`DEFAULT_EXACT_TO_HNSW_THRESHOLD`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VectorBackendKind {
    /// Deterministic in-memory exact cosine over every stored vector.
    Exact,
    /// Approximate nearest neighbor backend (not yet implemented in H0).
    Hnsw,
}

impl VectorBackendKind {
    /// Human-readable label, useful for logs and the dashboard.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Exact => "exact",
            Self::Hnsw => "hnsw",
        }
    }
}

/// One concrete vector-search backend chosen by [`select_backend_kind`].
///
/// Returned by [`VectorIndex::with_backend_kind`]. Holds either the
/// in-memory exact cosine [`VectorIndex`] or a boxed HNSW backend; both
/// impl [`VectorSearchBackend`] so callers can dispatch through the trait.
pub enum VectorBackend {
    /// Deterministic in-memory exact cosine over every stored vector.
    Exact(VectorIndex),
    /// Approximate nearest neighbor backend; only available with the
    /// `hnsw-backend` feature.
    #[cfg(feature = "hnsw-backend")]
    Hnsw(Box<dyn VectorSearchBackend>),
}

impl std::fmt::Debug for VectorBackend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Exact(index) => f.debug_tuple("Exact").field(index).finish(),
            #[cfg(feature = "hnsw-backend")]
            Self::Hnsw(_) => f
                .debug_tuple("Hnsw")
                .field(&"<dyn VectorSearchBackend>")
                .finish(),
        }
    }
}

impl VectorSearchBackend for VectorBackend {
    fn metadata(&self) -> &EmbeddingMetadata {
        match self {
            Self::Exact(index) => index.metadata(),
            #[cfg(feature = "hnsw-backend")]
            Self::Hnsw(backend) => backend.metadata(),
        }
    }

    fn document_count(&self) -> usize {
        match self {
            Self::Exact(index) => index.document_count(),
            #[cfg(feature = "hnsw-backend")]
            Self::Hnsw(backend) => backend.document_count(),
        }
    }

    fn upsert_document(&mut self, document: VectorDocument) -> Result<(), VectorIndexError> {
        match self {
            Self::Exact(index) => index.upsert_document(document),
            #[cfg(feature = "hnsw-backend")]
            Self::Hnsw(backend) => backend.upsert_document(document),
        }
    }

    fn remove_document(&mut self, document_id: &str) -> bool {
        match self {
            Self::Exact(index) => index.remove_document(document_id),
            #[cfg(feature = "hnsw-backend")]
            Self::Hnsw(backend) => backend.remove_document(document_id),
        }
    }

    fn get_vector(&self, document_id: &str) -> Option<Vec<f32>> {
        match self {
            Self::Exact(index) => index.get_vector(document_id),
            #[cfg(feature = "hnsw-backend")]
            Self::Hnsw(backend) => backend.get_vector(document_id),
        }
    }

    fn search(&self, query: &VectorQuery) -> Result<Vec<VectorSearchHit>, VectorIndexError> {
        match self {
            Self::Exact(index) => index.search(query),
            #[cfg(feature = "hnsw-backend")]
            Self::Hnsw(backend) => backend.search(query),
        }
    }

    fn search_filtered(
        &self,
        query: &VectorQuery,
        filter: &VectorFilter,
    ) -> Result<Vec<VectorSearchHit>, VectorIndexError> {
        match self {
            Self::Exact(index) => index.search_filtered(query, filter),
            #[cfg(feature = "hnsw-backend")]
            Self::Hnsw(backend) => backend.search_filtered(query, filter),
        }
    }
}

/// Default corpus size at which the [`VectorBackendKind`] selection switches
/// from [`VectorBackendKind::Exact`] to [`VectorBackendKind::Hnsw`].
///
/// The threshold is a single in-process default for the v1 release. Tier-
/// specific defaults (Hobby, Starter, Pro, Enterprise) will replace it once
/// multi-tenant work lands; see ROADMAP.md 1.0.0 Track B.
pub const DEFAULT_EXACT_TO_HNSW_THRESHOLD: usize = 50_000;

/// Pick the appropriate [`VectorBackendKind`] for one corpus size.
///
/// `Hnsw` is returned for any corpus at or above the threshold so the boundary
/// is "exclusively Hnsw" (an empty corpus, or one smaller than the threshold,
/// stays on the deterministic Exact backend).
pub fn select_backend_kind(document_count: usize) -> VectorBackendKind {
    if document_count >= DEFAULT_EXACT_TO_HNSW_THRESHOLD {
        VectorBackendKind::Hnsw
    } else {
        VectorBackendKind::Exact
    }
}

/// Pluggable backend for vector similarity search.
///
/// `VectorIndex` (the deterministic in-memory exact cosine) implements this
/// trait today. The upcoming HNSW backend will be a second implementation;
/// both will be reachable through the same `Box<dyn VectorSearchBackend>`
/// boundary so callers do not need to special-case the kind.
pub trait VectorSearchBackend {
    /// Return immutable embedding metadata for this backend.
    fn metadata(&self) -> &EmbeddingMetadata;

    /// Return number of stored vector documents.
    fn document_count(&self) -> usize;

    /// Insert or replace one document vector by id.
    fn upsert_document(&mut self, document: VectorDocument) -> Result<(), VectorIndexError>;

    /// Remove one document by id, returning `true` when it existed.
    fn remove_document(&mut self, document_id: &str) -> bool;

    /// Return a clone of the stored vector for one document id, if present.
    fn get_vector(&self, document_id: &str) -> Option<Vec<f32>>;

    /// Rank indexed vectors by similarity to the query vector.
    fn search(&self, query: &VectorQuery) -> Result<Vec<VectorSearchHit>, VectorIndexError>;

    /// Rank indexed vectors by similarity, restricted to documents that pass
    /// the supplied filter.
    ///
    /// The default implementation delegates to [`Self::search`] and then
    /// filters the results. Backends may override this for better performance
    /// (e.g. pre-filtering during an exact scan, or post-filtering with
    /// oversampling in an approximate backend).
    fn search_filtered(
        &self,
        query: &VectorQuery,
        filter: &VectorFilter,
    ) -> Result<Vec<VectorSearchHit>, VectorIndexError> {
        let hits = self.search(query)?;
        Ok(filter_hits(hits, filter))
    }
}

/// Post-filter a ranked hit list by a [`VectorFilter`].
fn filter_hits(hits: Vec<VectorSearchHit>, filter: &VectorFilter) -> Vec<VectorSearchHit> {
    if filter.allows_all() {
        return hits;
    }
    hits.into_iter()
        .filter(|hit| filter.allows(&hit.document_id))
        .collect()
}

/// In-memory deterministic cosine index for vector documents.
#[derive(Debug, Clone)]
pub struct VectorIndex {
    metadata: EmbeddingMetadata,
    documents: BTreeMap<String, Vec<f32>>,
}

impl VectorIndex {
    /// Create an empty index for one embedding space.
    pub fn new(metadata: EmbeddingMetadata) -> Self {
        Self {
            metadata,
            documents: BTreeMap::new(),
        }
    }

    /// Build an index from existing vector documents, choosing the backend by
    /// [`select_backend_kind`] on the resulting corpus size.
    ///
    /// In H1 the [`VectorBackendKind::Exact`] branch always returns a
    /// `VectorIndex`, and the [`VectorBackendKind::Hnsw`] branch returns a
    /// `Box<dyn VectorSearchBackend>` so the caller can hold either backend
    /// uniformly. The `Hnsw` branch is gated behind the `hnsw-backend`
    /// feature; without it we silently return an Exact backend so the
    /// build is still clean. Callers that need a real HNSW backend should
    /// enable the feature and rebuild.
    pub fn with_backend_kind(
        metadata: EmbeddingMetadata,
        documents: Vec<VectorDocument>,
        kind: VectorBackendKind,
    ) -> Result<VectorBackend, VectorIndexError> {
        match kind {
            VectorBackendKind::Exact => Ok(VectorBackend::Exact(Self::from_documents(
                metadata, documents,
            )?)),
            VectorBackendKind::Hnsw => {
                #[cfg(feature = "hnsw-backend")]
                {
                    let backend =
                        super::hnsw_backend::HnswBackend::from_documents(metadata, documents)?;
                    Ok(VectorBackend::Hnsw(Box::new(backend)))
                }
                #[cfg(not(feature = "hnsw-backend"))]
                {
                    let _ = metadata;
                    Ok(VectorBackend::Exact(Self::from_documents(
                        EmbeddingMetadata::new(
                            "stub",
                            documents.first().map(|d| d.vector.len()).unwrap_or(0),
                            "v0",
                        ),
                        documents,
                    )?))
                }
            }
        }
    }

    /// Build an index from existing vector documents.
    pub fn from_documents(
        metadata: EmbeddingMetadata,
        documents: Vec<VectorDocument>,
    ) -> Result<Self, VectorIndexError> {
        let mut index = Self::new(metadata);
        for document in documents {
            index.upsert_document(document)?;
        }
        Ok(index)
    }

    /// Return immutable embedding metadata for this index.
    pub fn metadata(&self) -> &EmbeddingMetadata {
        &self.metadata
    }

    /// Return number of stored vector documents.
    pub fn document_count(&self) -> usize {
        self.documents.len()
    }

    /// Insert or replace one document vector by id.
    pub fn upsert_document(&mut self, document: VectorDocument) -> Result<(), VectorIndexError> {
        validate_vector(
            &document.vector,
            self.metadata.dimension,
            Some(document.document_id.as_str()),
            "document",
        )?;
        self.documents.insert(document.document_id, document.vector);
        Ok(())
    }

    /// Remove one document by id, returning `true` when it existed.
    pub fn remove_document(&mut self, document_id: &str) -> bool {
        self.documents.remove(document_id).is_some()
    }

    /// Return a clone of the stored vector for one document id, if present.
    pub fn get_vector(&self, document_id: &str) -> Option<Vec<f32>> {
        self.documents.get(document_id).cloned()
    }

    /// Rank indexed vectors by cosine similarity to the query vector,
    /// optionally restricted by a [`VectorFilter`].
    pub fn search(&self, query: &VectorQuery) -> Result<Vec<VectorSearchHit>, VectorIndexError> {
        validate_vector(&query.vector, self.metadata.dimension, None, "query")?;

        let mut hits: Vec<VectorSearchHit> = self
            .documents
            .iter()
            .map(|(document_id, vector)| VectorSearchHit {
                document_id: document_id.clone(),
                score: cosine_similarity(&query.vector, vector).unwrap_or(0.0),
            })
            .collect();
        hits.sort_by(|left, right| {
            right
                .score
                .total_cmp(&left.score)
                .then_with(|| left.document_id.cmp(&right.document_id))
        });
        if hits.len() > query.limit {
            hits.truncate(query.limit);
        }
        Ok(hits)
    }

    /// Rank indexed vectors by cosine similarity, restricted by a
    /// [`VectorFilter`].
    ///
    /// This pre-filters during the linear scan: only matching documents are
    /// scored, so no work is wasted on excluded vectors. The returned list is
    /// still limited to `query.limit`.
    pub fn search_filtered(
        &self,
        query: &VectorQuery,
        filter: &VectorFilter,
    ) -> Result<Vec<VectorSearchHit>, VectorIndexError> {
        validate_vector(&query.vector, self.metadata.dimension, None, "query")?;

        if filter.allows_all() {
            return self.search(query);
        }

        let mut hits: Vec<VectorSearchHit> = self
            .documents
            .iter()
            .filter(|(document_id, _)| filter.allows(document_id))
            .map(|(document_id, vector)| VectorSearchHit {
                document_id: document_id.clone(),
                score: cosine_similarity(&query.vector, vector).unwrap_or(0.0),
            })
            .collect();
        hits.sort_by(|left, right| {
            right
                .score
                .total_cmp(&left.score)
                .then_with(|| left.document_id.cmp(&right.document_id))
        });
        if hits.len() > query.limit {
            hits.truncate(query.limit);
        }
        Ok(hits)
    }
}

impl VectorSearchBackend for VectorIndex {
    fn metadata(&self) -> &EmbeddingMetadata {
        &self.metadata
    }

    fn document_count(&self) -> usize {
        self.documents.len()
    }

    fn upsert_document(&mut self, document: VectorDocument) -> Result<(), VectorIndexError> {
        VectorIndex::upsert_document(self, document)
    }

    fn remove_document(&mut self, document_id: &str) -> bool {
        VectorIndex::remove_document(self, document_id)
    }

    fn get_vector(&self, document_id: &str) -> Option<Vec<f32>> {
        VectorIndex::get_vector(self, document_id)
    }

    fn search(&self, query: &VectorQuery) -> Result<Vec<VectorSearchHit>, VectorIndexError> {
        VectorIndex::search(self, query)
    }

    fn search_filtered(
        &self,
        query: &VectorQuery,
        filter: &VectorFilter,
    ) -> Result<Vec<VectorSearchHit>, VectorIndexError> {
        VectorIndex::search_filtered(self, query, filter)
    }
}
/// Failure while validating vectors or executing search.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VectorIndexError {
    /// Vector length does not match embedding metadata dimension.
    DimensionMismatch {
        /// Expected dimension from index metadata.
        expected: usize,
        /// Actual vector length.
        actual: usize,
        /// Context string: `"document"` or `"query"`.
        context: &'static str,
        /// Optional document id for document validation failures.
        document_id: Option<String>,
    },
    /// Vector contains `NaN` or `inf`.
    NonFiniteValue {
        /// Context string: `"document"` or `"query"`.
        context: &'static str,
        /// Optional document id for document validation failures.
        document_id: Option<String>,
        /// Index of the non-finite value.
        value_index: usize,
    },
}

impl fmt::Display for VectorIndexError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::DimensionMismatch {
                expected,
                actual,
                context,
                document_id,
            } => {
                if let Some(document_id) = document_id {
                    write!(
                        f,
                        "{context} vector for '{document_id}' has dimension {actual}, expected {expected}"
                    )
                } else {
                    write!(
                        f,
                        "{context} vector has dimension {actual}, expected {expected}"
                    )
                }
            }
            Self::NonFiniteValue {
                context,
                document_id,
                value_index,
            } => {
                if let Some(document_id) = document_id {
                    write!(
                        f,
                        "{context} vector for '{document_id}' contains non-finite value at index {value_index}"
                    )
                } else {
                    write!(
                        f,
                        "{context} vector contains non-finite value at index {value_index}"
                    )
                }
            }
        }
    }
}

impl Error for VectorIndexError {}

/// Compute cosine similarity for two vectors in the same space.
///
/// Returns `None` when dimensions differ or either vector has zero magnitude.
pub fn cosine_similarity(left: &[f32], right: &[f32]) -> Option<f32> {
    if left.len() != right.len() || left.is_empty() {
        return None;
    }

    let mut dot = 0.0_f32;
    let mut left_norm_sq = 0.0;
    let mut right_norm_sq = 0.0;
    for (left_value, right_value) in left.iter().zip(right.iter()) {
        dot += left_value * right_value;
        left_norm_sq += left_value * left_value;
        right_norm_sq += right_value * right_value;
    }

    if left_norm_sq == 0.0 || right_norm_sq == 0.0 {
        return None;
    }
    Some(dot / (left_norm_sq.sqrt() * right_norm_sq.sqrt()))
}

fn validate_vector(
    vector: &[f32],
    expected_dimension: usize,
    document_id: Option<&str>,
    context: &'static str,
) -> Result<(), VectorIndexError> {
    if vector.len() != expected_dimension {
        return Err(VectorIndexError::DimensionMismatch {
            expected: expected_dimension,
            actual: vector.len(),
            context,
            document_id: document_id.map(ToOwned::to_owned),
        });
    }
    for (value_index, value) in vector.iter().enumerate() {
        if !value.is_finite() {
            return Err(VectorIndexError::NonFiniteValue {
                context,
                document_id: document_id.map(ToOwned::to_owned),
                value_index,
            });
        }
    }
    Ok(())
}

/// `pub(super)` accessor for [`validate_vector`] used by the optional
/// HNSW backend. Crate-private, so user-facing callers go through
/// `VectorIndex` / `VectorSearchBackend`.
#[cfg(feature = "hnsw-backend")]
pub(super) fn validate_vector_public(
    vector: &[f32],
    expected_dimension: usize,
    document_id: Option<&str>,
    context: &'static str,
) -> Result<(), VectorIndexError> {
    validate_vector(vector, expected_dimension, document_id, context)
}

fn accumulate_hashed_feature(vector: &mut [f32], feature: &[u8], weight: f32) {
    if vector.is_empty() {
        return;
    }
    let digest = Sha256::digest(feature);
    let primary =
        u32::from_le_bytes([digest[0], digest[1], digest[2], digest[3]]) as usize % vector.len();
    let secondary =
        u32::from_le_bytes([digest[4], digest[5], digest[6], digest[7]]) as usize % vector.len();
    let sign = if digest[8] & 1 == 0 { 1.0 } else { -1.0 };
    vector[primary] += weight * sign;
    vector[secondary] += (weight * 0.5) * -sign;
}
